import {summarize,LABELS,csvValue} from '/assets/analytics-model.js';
const $=id=>document.getElementById(id), fmt=n=>new Intl.NumberFormat('es-UY',{maximumFractionDigits:1}).format(n), duration=s=>s>=60?`${Math.floor(s/60)} min ${Math.round(s%60)} s`:`${Math.round(s)} s`;
const OWNER='nicolasmendieta52@gmail.com';
let auth,authSdk,db,dbSdk,records=[],busy=false,generation=0;
const node=(tag,text,className)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;};
async function setup(){const config=await(await fetch('/notification-config.json')).json(),base='https://www.gstatic.com/firebasejs/11.10.0/';const [app,a,d]=await Promise.all([import(base+'firebase-app.js'),import(base+'firebase-auth.js'),import(base+'firebase-firestore.js')]);authSdk=a;dbSdk=d;const instance=app.initializeApp(config.firebase,'ceibos-panel');auth=a.getAuth(instance);await a.setPersistence(auth,a.browserSessionPersistence);db=d.getFirestore(instance);a.onAuthStateChanged(auth,user=>{
 generation++;records=[];for(const id of ['metrics','daily','sections','actions','devices','origins','browsers','systems','visits'])$(id).replaceChildren();$('status').textContent='';$('dashboard').hidden=true;$('login').hidden=false;$('logout').hidden=!user;
 if(!user)return;
 if(user.email?.toLowerCase()!==OWNER||!user.emailVerified){$('login-status').textContent='Esta cuenta no tiene acceso al panel. Cerrá sesión e ingresá con la cuenta autorizada.';return;}
 $('account').textContent=user.email;$('login').hidden=true;$('dashboard').hidden=false;
 try{if(localStorage.getItem('ceibos_metrics_exclude')===null)localStorage.setItem('ceibos_metrics_exclude','1');$('exclude').checked=localStorage.getItem('ceibos_metrics_exclude')==='1';}catch{}
 load();
 });}
$('signin').addEventListener('click',async()=>{if(!auth)return;$('signin').disabled=true;$('login-status').textContent='Abriendo Google…';try{await authSdk.signInWithPopup(auth,new authSdk.GoogleAuthProvider());}catch(e){$('login-status').textContent=e.code==='auth/popup-closed-by-user'?'Se cerró el acceso. Podés volver a intentarlo.':'No se pudo ingresar. Permití la ventana de Google y probá otra vez.';}finally{$('signin').disabled=false;}});
$('logout').addEventListener('click',()=>authSdk.signOut(auth));
$('exclude').addEventListener('change',()=>{try{localStorage.setItem('ceibos_metrics_exclude',$('exclude').checked?'1':'0');}catch{}});
function bars(id,values){const host=$(id);host.replaceChildren();const sorted=Object.entries(values).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]).slice(0,12),max=sorted[0]?.[1]||1;if(!sorted.length){host.append(node('p','Todavía no hay actividad registrada.','empty'));return;}for(const [key,n]of sorted){const row=node('div',undefined,'bar-row'),track=node('div',undefined,'bar-track'),fill=node('div',undefined,'bar-fill');fill.style.width=`${n/max*100}%`;track.append(fill);row.append(node('span',LABELS[key]||key),track,node('strong',fmt(n)));host.append(row);}}
function render(){const stats=summarize(records);$('metrics').replaceChildren();const metrics=[['Visitas',fmt(stats.visits),'Cargas de página registradas'],['Visitantes aproximados',fmt(stats.visitors),'Navegadores distintos'],['Actividad reciente',fmt(stats.active),'Visitas activas en los últimos 2 min'],['Tiempo activo medio',duration(stats.visits?stats.seconds/stats.visits:0),'Con página visible y actividad reciente'],['Interacciones',fmt(stats.interactions),'Clics y selecciones'],['Visitas con interacción',`${fmt(stats.visits?stats.engaged/stats.visits*100:0)}%`,'Al menos 10 s activos o un clic']];for(const [label,value,note]of metrics){const el=node('article',undefined,'metric');el.append(node('span',label),node('strong',value),node('small',note));$('metrics').append(el);}
 for(const id of ['sections','actions','devices','browsers','systems','origins'])bars(id,stats[id]);
 $('daily').replaceChildren();const days=Number($('period').value),calendar=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Montevideo'}),max=Math.max(1,...Object.values(stats.days));for(let i=days;i>=0;i--){const key=calendar.format(new Date(Date.now()-i*86400000)),n=stats.days[key]||0,el=node('div',undefined,'day'),bar=node('div',undefined,'column');bar.style.height=`${n/max*120}px`;el.title=`${key}: ${n} visitas`;el.append(node('b',String(n)),bar,node('span',key.slice(5).split('-').reverse().join('/')));$('daily').append(el);}
 $('visits').replaceChildren();if(!records.length)$('visits').append(node('p','Las visitas aparecerán aquí cuando alguien acepte la medición y use la web.','empty'));
 for(const v of records.slice(0,50)){const item=node('details',undefined,'visit'),summary=node('summary'),stamp=new Intl.DateTimeFormat('es-UY',{dateStyle:'short',timeStyle:'short',timeZone:'America/Montevideo'}).format(new Date(v.createdMs));summary.append(node('strong',stamp),node('span',v.device+' · '+v.browser),node('span',duration(v.activeSeconds)),node('span',`${v.interactions} interacciones · ${v.scrollDepth}% recorrido`));const content=node('div',undefined,'visit-content');const description=node('p',`Visita ${v.id.slice(0,8)} · ${v.os}\nOrigen: ${v.referrer}\nIdioma: ${v.language} · Zona horaria del navegador: ${v.timeZone}\nPágina: ${v.path}`);description.style.whiteSpace='pre-line';const actions=node('p');actions.textContent='Secciones: '+Object.entries(v.sections||{}).filter(([,n])=>n>0).map(([k])=>LABELS[k]||k).join(', ')+'. Interacciones: '+(Object.entries(v.actions||{}).filter(([,n])=>n>0).map(([k,n])=>(LABELS[k]||k)+' ('+n+')').join(', ')||'Ninguna')+'.';content.append(description,actions);item.append(summary,content);$('visits').append(item);}
}
async function load(){if(busy||auth?.currentUser?.email?.toLowerCase()!==OWNER||document.hidden)return;busy=true;const version=generation;$('refresh').disabled=true;$('period').disabled=true;$('status').textContent='Consultando estadísticas privadas…';try{const {collection,query,where,orderBy,limit,getDocs,Timestamp}=dbSdk;const from=Timestamp.fromMillis(Date.now()-Number($('period').value)*86400000);const snap=await getDocs(query(collection(db,'analyticsVisits'),where('createdAt','>=',from),orderBy('createdAt','desc'),limit(2000)));if(version!==generation)return;records=snap.docs.map(doc=>{const v=doc.data();return {...v,id:doc.id,createdMs:v.createdAt.toMillis(),lastSeenMs:v.lastSeen.toMillis()};});render();$('status').textContent=`Actualizado ${new Date().toLocaleTimeString('es-UY')} · ${records.length} visitas en el período.${records.length===2000?' Se muestran las 2.000 más recientes; elegí un período menor para evitar el límite.':''}`;}catch(e){if(version===generation)$('status').textContent=e.code==='permission-denied'?'Acceso denegado por la base de datos. Solo la cuenta autorizada puede consultar estadísticas.':'No se pudo actualizar. Revisá la conexión y volvé a intentar.';}finally{busy=false;$('refresh').disabled=false;$('period').disabled=false;}}
$('refresh').addEventListener('click',load);$('period').addEventListener('change',()=>{generation++;load();});setInterval(load,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});
$('export').addEventListener('click',()=>{const rows=[['Fecha Uruguay','Visita anónima','Dispositivo','Navegador','Sistema','Origen','Idioma','Zona horaria','Segundos activos','Interacciones','Recorrido %'],...records.map(v=>[new Date(v.createdMs).toLocaleString('es-UY',{timeZone:'America/Montevideo'}),v.id.slice(0,8),v.device,v.browser,v.os,v.referrer,v.language,v.timeZone,v.activeSeconds,v.interactions,v.scrollDepth])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(csvValue).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=node('a');a.href=url;a.download=`ceibos-visitas-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
setup().catch(()=>{$('login-status').textContent='No se pudo conectar con el acceso seguro. Recargá la página para volver a intentar.';});
